apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grantvoss.duckdns.org
  namespace: teleport-app
spec:
  dnsNames:
  - 'grantvoss.duckdns.org'
  issuerRef:
    name: duckdns-letsencrypt-staging 
    kind: ClusterIssuer
  secretName: grantvoss.duckdns.org-tls
